<?php
/********
Post Type
********/
include('posttypes/banner.php');
include('posttypes/press.php');
include('posttypes/newsletter.php');
include('posttypes/retailers.php');
include('posttypes/work_with_us.php');
/********
Listing
********/
include('includes/theme_option.php');
include('includes/contact_list.php');
include('includes/newsletter_listing.php');
include('includes/pagination.php');
include('includes/work_with_us_listing.php');
/********
Metaboxes
********/
include('metaboxes/banner_more.php');
include('metaboxes/order_field_meta.php');
include('metaboxes/product_meta.php');
include('metaboxes/author_meta.php');
include('metaboxes/url_link.php');
include('metaboxes/short_description.php');
include('metaboxes/short_codes_list.php');
include('metaboxes/img_desc_meta.php');
